FROM mysql:latest
ENV MYSQL_DATABASE=DivinoSeas_db
ENV MYSQL_ROOT_PASSWORD=DivinoSeas_password
ENV MYSQL_USER=DivinoSeas_user
ENV MYSQL_PASSWORD=DivinoSeas_password
COPY bd.sql ./docker-entrypoint-initdb.d/